### ISSUE TITLE
-U option not work with --fromtabfile

### ISSUE THREAD

**Issue by jack6th** [Old-Man-Programmer/tree#5]
tree v2.1.1

Input bash command
`echo $'Leve 1\n\tItem 3\n\tItem 2\n\tItem 1' | tree --fromtabfile -U --noreport`
output
```
.
└── Leve 1
    ├── Item 1
    ├── Item 2
    └── Item 3
```
User expect
```
.
└── Leve 1
    ├── Item 3
    ├── Item 2
    └── Item 1
```

**Comment by Old-Man-Programmer** [comment]
This should be fixed in 2.1.3.
