### ISSUE TITLE
Allow no space between `-L` and its argument

### ISSUE THREAD

**Issue by tgross35** [Old-Man-Programmer/tree#7]
For example, this:

```
root@72c513cae592:/# tree -L1
tree: Missing argument to -L option.
```

Should act the same as this:

```
root@72c513cae592:/# tree -L 1
.
|-- bin -> usr/bin
|-- boot
|-- dev
|-- etc
|-- home
|-- lib -> usr/lib
|-- lib64 -> usr/lib64
|-- media
|-- mnt
|-- opt
|-- proc
|-- root
|-- run
|-- sbin -> usr/sbin
|-- srv
|-- sys
|-- tmp
|-- usr
`-- var

20 directories, 0 files
```

Probably the same for `-o` or any single-dash options that take an argument, I think this is fairly standard, just ever so slightly easier to type.

Awesome little tool this is, thanks for maintaining it :)

**Comment by Old-Man-Programmer** [comment]
This has been added to 2.1.3.

**Comment by tgross35** [comment]
Excellent, thank you!
