### ISSUE TITLE
Feature Request: for MD5 Support

### ISSUE THREAD

**Issue by jerrin92** [Old-Man-Programmer/tree#8]
Could you add support for md5 sums of files?

```
$ tree . -L 1 --md5
.
|── basic_typer.py (82f113cdddcbb92cc176acf64df0ad4e)
|── typer_env (Is a directory)
|── typer_exit.py (08a127d9c289eda5e0ffbf6bb8ebbe07)
└── typer_exit_usernames.yaml (ecdb6d9440a961748f594933784968df)
```

**Comment by Old-Man-Programmer** [comment]
This seems a bit too obscure a use case.  You can get most of what you want I think with find / awk and the --fromfile option:
> find -type f -a -exec md5sum {} \; | awk '{print $2 " (" $1 ")"}' | tree --fromfile

This does omit directories with nothing in them however.

**Comment by jerrin92** [comment]
Cool! works like a charm! 😄

**Comment by polluks** [comment]
This works for macOS:
`find . -type f -a -exec md5sum {} \; | awk '{print $2 " (" $1 ")"}' | tree --fromfile`
